# Generated by Django 6.0.5 on 2026-06-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('prediction', models.CharField(help_text='e.g., Home Win, Over 2.5, GG', max_length=100)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match_date', models.DateField(help_text='The date the game will be played')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
