# Generated by Django 6.0.5 on 2026-06-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedgame',
            name='created_at',
        ),
        migrations.AddField(
            model_name='predictedgame',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='predictedgame',
            name='match_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='predictedgame',
            name='odds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='predictedgame',
            name='prediction',
            field=models.CharField(max_length=100),
        ),
    ]
