# Generated by Django 6.0.5 on 2026-06-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophet', '0002_remove_predictedgame_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedgame',
            name='sportybet_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SportyBet Code'),
        ),
    ]
